---
- name: Set hostname to inventory hostname
  hostname: 
    name: "{{inventory_hostname}}"

- name: Update the mirrolist
  copy:
    src:  ../files/sources.list
    dest: /etc/apt/sources.list

- name: Set timezone to America/Sao_Paulo
  timezone:
    name: America/Sao_Paulo

- name: Ensure GB-UTF8 locale exists
  locale_gen:
    name: en_GB.UTF-8
    state: present

- name: Disable swap on Raspbian
  apt:
    name: dphys-swapfile
    state: absent
    purge: yes

- name: Disable HDMI
  lineinfile:
    dest: /etc/rc.local
    regexp: "^/usr/bin/tvservice"
    line: "/usr/bin/tvservice -o"
    insertbefore: "^exit"
    state: present
    
- name: Copy Alias to Host
  copy:
    src:  ../files/.zshalias
    dest: /home/pi/.zshalias

- name: Source de Alias
  shell: echo source /home/pi/.zshalias >> /home/pi/.profile

- name: Update and Upgrade system
  apt:
    autoremove: yes
    update_cache: yes
    upgrade: dist
  notify: Reboot
